name: EccubeApi
code: EccubeApi
version: 1.0.2
event: EccubeApiEvent
service:
    - EccubeApiServiceProvider
orm.path:
    - /Resource/doctrine
    - /Resource/doctrine/oauth2
    - /Resource/doctrine/oauth2/openid

